name: Build LaTeX document
on: 
  # push:
  #   branches:
  #     - master
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
        
      - name: Generate core-pubs
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/hoanganhduc/texlive:latest
          options: -u root -v ${{ github.workspace }}:/core
          run: |
            source /root/.zshrc
            cd /core
            make
          
      - name: set env
        run: echo "NOW=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.NOW }}
          tag_name: ${{ env.NOW }}
          files: |
            core-pubs.pdf
          fail_on_unmatched_files: true
